### ISSUE TITLE
SPIClass mySPI

### ISSUE THREAD

**Issue by ghost** [rbarreiros/FV1-Touch#1]
on line 117
SPIClass mySPI(1); //Create an SPI instance on default SPI port (SPI 1)
is missing the (1)
wouldn't compile without it

**Comment by rbarreiros** [comment]
I'm surprised it compiled with it, because you're using Dan drown stm32 Arduino port that's why it wouldn't compile, as Dan drown stm32 port requires the spi port in the constructor, but, bounce2 doesn't compile with that stm32 port, hence I use this (more compatible with latest Arduino libraries) stm32duino port:

https://github.com/stm32duino

With this one, spi constructor with default settings doesn't need any parameter and all libs compile properly.

**Comment by rbarreiros** [comment]
Check the file header.
